#!/bin/bash

# Install passh
# curl -k https://raw.githubusercontent.com/brunomgalmeida/passh/master/passh.c >passh.c
# gcc passh.c -o passh && chmod +x passh && sudo mv passh /usr/local/bin && rm passh.c

# alias ssh='ssh_wrapper'
# Encrypt: printf "password" | gpg -c | base64 -w 0
# Decrypt: printf "jA0ECQMCpgfs205Ngmr/0j0BZ9zL9Z+3F18oK74vN/rJehoAhRAfRcc9r8WU8SpukRGsDJEMdi3BxPeR7APXZq412r79aYnDCFIXIzwg" | base64 -d | gpg -d -q

# https://askubuntu.com/questions/87956/can-you-set-passwords-in-ssh-config-to-allow-automatic-login
# Create a list of password in a hashmap format
# > https://stackoverflow.com/questions/1494178/how-to-define-hash-tables-in-bash
# sed -rn "s/^\s*#(Password[0-9])\s+=\s+(.*)/\1 \2/p"  ~/.ssh/config

function getPass () {
    # Read a list of passwords int he format `#Password[0-9]=passwordhere` from the $USER ssh config file
    OIFS=$IFS; IFS=';'
    PASSWORD_LIST=$( sed -rn "s/^\s*#\s*(Password[0-9])\s+=\s+(.*)/\1 \2/p"  ~/.ssh/config )
    IFS=$OIFS
    echo "$PASSWORD_LIST" | grep "Password$1" | awk -F ' ' '{ print $2 }'
}

#TODO How to extract password from ssh config inheritance

# Extract the value that follows the text '#Password '
password=$(awk 'BEGIN {
    # Collect the SSH arguments as keys of a dictionary, so that we can easily check for inclusion.
    for (i = 2; i < ARGC; i++) {
        # Ignore arguments that start with - as there are most likely options
        if (! match (ARGV[i], /^-/ ) ){
            sshArgs[ARGV[i]] = ARGV[i]
            # printf ">>ARG=%s\n", ARGV[i]                          # DEBUG - show parsed values
        }
    }
    # Only process the first argument; all others are the command-line arguments given to ssh.
    ARGC = 2
    # for (key in sshArgs) { print sshArgs[key] }                   # DEBUG - show all values in array
}
$1 == "#Password" && inhost {
    for(i=2;i<=NF;i+=1) {
        if (i > 2)
            printf ""
        else
            printf $i
    }
}
/^\s*Host\s/ {
    for (key in sshArgs) {                                          # For every entry in sshArgs
        #printf ">> Checking line %s\n", $0                          # DEBUG - show the host that we are working with
        split($0, hosts)                                            # Store in the variable host all the alias, split by space
        # for (key in hosts) { print hosts[key] }
        for (h in hosts){                                           # For every alias in the Host
            p#rintf ">> Comparing %s with %s\n", hosts[h], key       # DEBUG - Show what is being compared
            if ( key ~ hosts[h] ){
                #printf ">> MATCH FOUND on line %s\n", $0            # DEBUG - display the entries that match
                inhost=1
            } else{
                inhost=0
            }
        }
    }
}' ~/.ssh/config "$@")

# To test the command above, simply copy from AWK onwards and add `~/.ssh/config ssh coral-prod --list --help` to the end

# If the password is a single digit, then fetch the Password$ID, otherwise use the value returned from the parsing
[[ $password =~ [0-9]{1} ]] && p=$( getPass $password ) || p=$password

# Check if there is a local password ($p), if not defaults to Password0
decode=${p:-$( getPass 0 )}

# IF gpg-agent version >2, whe should use gpg2
# https://unix.stackexchange.com/questions/231386/how-to-make-gpg-find-gpg-agent

# Defaults to gpg2 if found
gpg=$( which gpg2 )

if [ -z $gpg ]; then
    # Could not find gpg2, then use gpg
    gpg=$( which gpg )
fi

if [ -z $gpg ]; then
    printf "gpg not found. Exiting...\n"
    exit 1
fi

if [ "$decode" ]; then
    passw=$( printf "$decode" | base64 -d | $gpg -d -q )
    passh -c1 -p "$passw" ssh "$@"
else
    ssh "$@"
fi
